version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  labels:
    - "npm"
    - "dependencies"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
